# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SKT',
                'doc_host': 'https://zegaouiy.github.io',
                'git_url': 'https://github.com/zegaouiy/SKT',
                'lib_path': 'SKT'},
  'syms': {'SKT.core': {'SKT.core.foo': ('core.html#foo', 'SKT/core.py')}, 'SKT.skt': {'SKT.skt.foo': ('core.html#foo', 'SKT/skt.py')}}}
